FROM cgr.dev/chainguard/jre@sha256:9f3bd12dad2597103dadb6f5b661ad2b547266e11e6973c1b8b4f8843ff55cf6

WORKDIR /home/languageTool

COPY libs/ libs
COPY META-INF/ META-INF
COPY org/ org
COPY languagetool-server.jar .
COPY server.properties .

EXPOSE 8181/tcp

ENTRYPOINT [ "java", "-cp", "languagetool-server.jar", "org.languagetool.server.HTTPServer", "--config", "server.properties", "--port", "8181", "--allow-origin", "--public" ]
